version: '3.1'
# Para rodar o mysql no container gerado no docker compose, use:
#     docker compose exec db bash
#       mysql -proot -u root -h localhost -D loja_virtual
#       mysql -uroot -proot -hlocalhost -Dloja_virtual
#         (sendo -p o parâmetro pra indicar a senha do banco de dados. Repare
#          que não há espaço entre o parâmetro e o valor na segunda linha.)
    
#     OU

#     docker compose exec db mysql -proot
#         (O que vem depois do nome do container, DB, é o comando pra rodar).

services:
  db:
    image: mysql:8.0.18
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - D:\mysql:/var/lib/mysql
    ports:
      - 3306:3306
    # docker run -d -p "3306:3306" -e MYSQL_ROOT_PASSWORD=root -e MYSQL_ROOT_HOST=% --name mysql -v "D:\mysql:/var/lib/mysql" mysql:8.0.18

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
    # docker run --name myadmin -d --link mysql:db -p 8080:80 phpmyadmin
